# Generated by Django 5.0.3 on 2026-06-22 09:17
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('address_line1', models.CharField(blank=True, default='', max_length=255)),
                ('address_line2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='Tennessee', max_length=50)),
                ('zip_code', models.CharField(blank=True, default='', max_length=10)),
                ('notification_preference', models.CharField(
                    choices=[('email', 'Email'), ('sms', 'SMS / Text'), ('both', 'Email & SMS'), ('none', 'None')],
                    default='email', max_length=10,
                )),
                ('email_court_reminders', models.BooleanField(default=True)),
                ('email_deadline_alerts', models.BooleanField(default=True)),
                ('email_case_updates', models.BooleanField(default=True)),
                ('sms_court_reminders', models.BooleanField(default=False)),
                ('sms_deadline_alerts', models.BooleanField(default=False)),
                ('onboarding_complete', models.BooleanField(default=False)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='profile',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
