"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path
from dotenv import load_dotenv

load_dotenv(Path(__file__).resolve().parent.parent / ".env")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "use-env-to-change-me"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "tenantguard.net",
    "www.tenantguard.net",
    "dev.tenantguard.net",
    "backend",
    "frontend",
]

# Trust the X-Forwarded-Proto header from nginx so Django knows requests are HTTPS
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Required for CSRF to work when Django is behind an HTTPS reverse proxy
CSRF_TRUSTED_ORIGINS = [
    "https://tenantguard.net",
    "https://www.tenantguard.net",
    "https://dev.tenantguard.net",
]


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    # 3rd party
    "corsheaders",
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.github",
    "dj_rest_auth",
    "dj_rest_auth.registration",
    "taggit",
    "django_summernote",
    # custom
    "authentication.apps.AuthenticationConfig",
    "blog.apps.BlogConfig",
    "chat.apps.ChatConfig",
    "intake.apps.IntakeConfig",
    "stafftodo.apps.StafftodoConfig",
    "google_analytics_django",
]

SITE_ID = 1

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "google_analytics_django.middleware.GoogleAnalyticsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

_db_options = {}
if os.getenv("DB_SSLMODE"):
    _db_options["sslmode"] = os.getenv("DB_SSLMODE")
if os.getenv("DB_SSLROOTCERT"):
    _db_options["sslrootcert"] = os.getenv("DB_SSLROOTCERT")
if os.getenv("DB_SSLCERT"):
    _db_options["sslcert"] = os.getenv("DB_SSLCERT")
if os.getenv("DB_SSLKEY"):
    _db_options["sslkey"] = os.getenv("DB_SSLKEY")

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "tenantguard_db_name"),
        "USER": os.getenv("DB_USER", "tenantguard_db_user"),
        "PASSWORD": os.getenv("DB_PASSWORD", ""),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432"),
        "OPTIONS": _db_options,
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# django-cors-headers
# https://pypi.org/project/django-cors-headers/

if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "https://dev.tenantguard.net",
        "https://tenantguard.net",
        "https://www.tenantguard.net",
        "http://backend:8000",
        "http://frontend:3000",
    ]


# djangorestframework
# https://www.django-rest-framework.org/

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ]
}

# django-all-auth
# https://django-allauth.readthedocs.io/en/latest/index.html

ACCOUNT_EMAIL_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = "none"

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": "<your google client id>",
            "secret": "<your google secret>",
            "key": "",  # leave empty
        },
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
        "VERIFIED_EMAIL": True,
    },
    "github": {
        "APP": {
            "client_id": "<your github client id>",
            "secret": "<your github secret>",
            "key": "",
        },
        "SCOPE": [
            "user",
            "repo",
            "read:org",
        ],
    },
}

FRONTEND_URL = os.environ.get("FRONTEND_URL", "http://localhost:3000")

JAZZMIN_SETTINGS = {
    "site_title": "TenantGuard Admin",
    "site_header": "TenantGuard",
    "site_brand": "TenantGuard",
    "welcome_sign": "Welcome to TenantGuard Administration",
    "copyright": "TenantGuard Ltd",
    "search_model": ["auth.User", "blog.Post"],
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"model": "auth.User"},
        {
            "name": "AI Blog Writer",
            "url": "ai-generator",
            "permissions": ["auth.view_user"],
        },
        {"app": "blog"},
        {
            "name": "← View Site",
            "url": FRONTEND_URL,
            "new_window": True,
        },
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "blog.Post": "fas fa-blog",
        "blog.Category": "fas fa-folder",
        "blog.Tag": "fas fa-tags",
        "blog.Comment": "fas fa-comments",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": False,
    "custom_css": None,
    "custom_js": None,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
}

# dj-rest-auth & djangorestframework-simplejwt
# https://dj-rest-auth.readthedocs.io/en/latest/index.html
# https://django-rest-framework-simplejwt.readthedocs.io/en/latest/index.html

REST_AUTH = {
    "USE_JWT": True,
    "JWT_AUTH_HTTPONLY": False,
    "USER_DETAILS_SERIALIZER": "authentication.serializers.UserDetailsSerializer",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": True,
    "SIGNING_KEY": "jwt-insecure-z6dh*i8cjajq$o6lg-@$%3v06vpl!irr9+v0=+d&5d$f#-(&#t",
    "ALGORITHM": "HS512",
}

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Google Cloud Storage for media files.
# On GCE VMs, credentials are picked up automatically via the instance service account.
# For local dev, either leave GCS_MEDIA_BUCKET unset (uses local filesystem above),
# or run `gcloud auth application-default login` and set GCS_MEDIA_BUCKET.
_GCS_BUCKET = os.environ.get("GCS_MEDIA_BUCKET")
if _GCS_BUCKET:
    # Use the modern STORAGES dict (required for Django 5.x).
    # querystring_auth=False → generate plain public HTTPS URLs.
    # Do NOT set default_acl="publicRead" — that conflicts with Uniform Bucket-Level
    # Access (GCS default).  Instead grant allUsers Storage Object Viewer at the
    # bucket IAM level (as documented in docs/gcs-env-setup.md).
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.gcloud.GoogleCloudStorage",
            "OPTIONS": {
                "bucket_name": _GCS_BUCKET,
                "querystring_auth": False,  # public unsigned URLs
            },
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    GS_BUCKET_NAME = _GCS_BUCKET  # kept for any direct settings reads
    MEDIA_URL = f"https://storage.googleapis.com/{_GCS_BUCKET}/"

# Summernote (inline content image uploads in admin)
# Organise attachments under blog/content_images/ in whichever storage backend
# is active (local filesystem in dev, GCS bucket in production).
SUMMERNOTE_CONFIG = {
    "summernote": {
        "width": "100%",
        "height": "480",
    },
    "attachment_upload_to": "blog/content_images/",
    "attachment_filesize_limit": 5 * 1024 * 1024,  # 5 MB
}


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
