import React, { useState, useEffect, useCallback } from 'react';
import { useAuth } from '../hooks/useAuth';
import { API_BASE_URL } from '../lib/apiBase.js';

const ApprovalQueue = () => {
  const { accessToken, isAdmin } = useAuth();
  const [pendingPosts, setPendingPosts] = useState([]);
  const [statistics, setStatistics] = useState(null);
  const [selectedPost, setSelectedPost] = useState(null);
  const [rejectionReason, setRejectionReason] = useState('');
  const [approvalNotes, setApprovalNotes] = useState('');
  const [loading, setLoading] = useState(true);

  const adminFlag = isAdmin();

  const fetchPendingPosts = useCallback(async () => {
    try {
      const response = await fetch(`${API_BASE_URL}/api/blog/approval/pending`, {
        headers: {
          'Authorization': `Bearer ${accessToken}`
        }
      });
      
      if (response.ok) {
        const data = await response.json();
        setPendingPosts(data.pending_posts);
      }
    } catch (error) {
      console.error('Error fetching pending posts:', error);
    } finally {
      setLoading(false);
    }
  }, [accessToken]);

  const fetchStatistics = useCallback(async () => {
    try {
      const response = await fetch(`${API_BASE_URL}/api/blog/approval/statistics`, {
        headers: {
          'Authorization': `Bearer ${accessToken}`
        }
      });
      
      if (response.ok) {
        const data = await response.json();
        setStatistics(data);
      }
    } catch (error) {
      console.error('Error fetching statistics:', error);
    }
  }, [accessToken]);

  useEffect(() => {
    if (adminFlag) {
      fetchPendingPosts();
      fetchStatistics();
    }
  }, [adminFlag, fetchPendingPosts, fetchStatistics]);

  

  const handleApprove = async (postId, publishImmediately = true) => {
    try {
      const response = await fetch(`${API_BASE_URL}/api/blog/approval/approve/${postId}`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${accessToken}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          notes: approvalNotes,
          publish_immediately: publishImmediately
        })
      });
      
      if (response.ok) {
        // Refresh lists
        fetchPendingPosts();
        fetchStatistics();
        setSelectedPost(null);
        setApprovalNotes('');
        alert('Post approved successfully!');
      } else {
        const data = await response.json();
        alert(`Error: ${data.error}`);
      }
    } catch (error) {
      console.error('Error approving post:', error);
      alert('Failed to approve post');
    }
  };

  const handleReject = async (postId) => {
    if (!rejectionReason.trim()) {
      alert('Please provide a rejection reason');
      return;
    }
    
    try {
      const response = await fetch(`${API_BASE_URL}/api/blog/approval/reject/${postId}`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${accessToken}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          reason: rejectionReason
        })
      });
      
      if (response.ok) {
        fetchPendingPosts();
        fetchStatistics();
        setSelectedPost(null);
        setRejectionReason('');
        alert('Post rejected');
      } else {
        const data = await response.json();
        alert(`Error: ${data.error}`);
      }
    } catch (error) {
      console.error('Error rejecting post:', error);
      alert('Failed to reject post');
    }
  };

  if (!isAdmin()) {
    return (
      <div className="p-6 text-center">
        <p className="text-red-600">Admin access required</p>
      </div>
    );
  }

  if (loading) {
    return (
      <div className="p-6 text-center">
        <div className="inline-block animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
      </div>
    );
  }

  return (
    <div className="max-w-7xl mx-auto p-6">
      <div className="mb-8">
        <h1 className="text-3xl font-bold mb-2">Blog Post Approval Queue</h1>
        <p className="text-gray-600">Review and approve posts generated by Manus or submitted by editors</p>
      </div>

      {/* Statistics Dashboard */}
      {statistics && (
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-8">
          <div className="bg-yellow-50 border-2 border-yellow-200 p-6 rounded-lg">
            <div className="text-3xl font-bold text-yellow-700">{statistics.pending_count}</div>
            <div className="text-sm text-yellow-600">Pending Approval</div>
          </div>
          <div className="bg-green-50 border-2 border-green-200 p-6 rounded-lg">
            <div className="text-3xl font-bold text-green-700">{statistics.approved_count}</div>
            <div className="text-sm text-green-600">Approved</div>
          </div>
          <div className="bg-blue-50 border-2 border-blue-200 p-6 rounded-lg">
            <div className="text-3xl font-bold text-blue-700">{statistics.published_count}</div>
            <div className="text-sm text-blue-600">Published</div>
          </div>
          <div className="bg-red-50 border-2 border-red-200 p-6 rounded-lg">
            <div className="text-3xl font-bold text-red-700">{statistics.rejected_count}</div>
            <div className="text-sm text-red-600">Rejected</div>
          </div>
        </div>
      )}

      {/* Pending Posts List */}
      <div className="bg-white rounded-lg shadow">
        <div className="p-6 border-b border-gray-200">
          <h2 className="text-xl font-semibold">Posts Awaiting Approval ({pendingPosts.length})</h2>
        </div>

        {pendingPosts.length === 0 ? (
          <div className="p-12 text-center text-gray-500">
            <svg className="w-16 h-16 mx-auto mb-4 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            <p className="text-lg font-medium">No posts pending approval</p>
            <p className="text-sm mt-2">All caught up! New posts will appear here when submitted.</p>
          </div>
        ) : (
          <div className="divide-y divide-gray-200">
            {pendingPosts.map(post => (
              <div key={post.id} className="p-6 hover:bg-gray-50">
                <div className="flex justify-between items-start">
                  <div className="flex-1">
                    <h3 className="text-lg font-semibold mb-2">{post.title}</h3>
                    
                    <div className="flex gap-2 mb-3">
                      <span className={`px-2 py-1 rounded text-xs font-medium ${
                        post.category === 'technical' ? 'bg-blue-100 text-blue-800' : 'bg-green-100 text-green-800'
                      }`}>
                        {post.category === 'technical' ? 'Technical Update' : 'Market Research'}
                      </span>
                      <span className="px-2 py-1 rounded text-xs font-medium bg-purple-100 text-purple-800">
                        {post.generated_by || 'Unknown'}
                      </span>
                      {post.generation_source && (
                        <span className="px-2 py-1 rounded text-xs font-medium bg-gray-100 text-gray-800">
                          {post.generation_source}
                        </span>
                      )}
                    </div>
                    
                    {post.excerpt && (
                      <p className="text-sm text-gray-600 mb-2 line-clamp-2">{post.excerpt}</p>
                    )}
                    
                    <div className="text-xs text-gray-500">
                      <span>By {post.author}</span>
                      <span className="mx-2">•</span>
                      <span>Submitted {new Date(post.submitted_for_approval_at).toLocaleString()}</span>
                    </div>
                  </div>
                  
                  <div className="flex gap-2 ml-4">
                    <button
                      onClick={() => setSelectedPost(post)}
                      className="px-4 py-2 bg-gray-100 text-gray-700 rounded hover:bg-gray-200 text-sm font-medium"
                    >
                      Review
                    </button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Post Review Modal */}
      {selectedPost && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-lg max-w-4xl w-full max-h-[90vh] overflow-y-auto">
            <div className="p-6 border-b border-gray-200 sticky top-0 bg-white">
              <div className="flex justify-between items-start">
                <div>
                  <h2 className="text-2xl font-bold mb-2">{selectedPost.title}</h2>
                  <div className="flex gap-2">
                    <span className={`px-2 py-1 rounded text-xs font-medium ${
                      selectedPost.category === 'technical' ? 'bg-blue-100 text-blue-800' : 'bg-green-100 text-green-800'
                    }`}>
                      {selectedPost.category === 'technical' ? 'Technical Update' : 'Market Research'}
                    </span>
                    <span className="px-2 py-1 rounded text-xs font-medium bg-purple-100 text-purple-800">
                      Generated by: {selectedPost.generated_by || 'Unknown'}
                    </span>
                  </div>
                </div>
                <button
                  onClick={() => {
                    setSelectedPost(null);
                    setApprovalNotes('');
                    setRejectionReason('');
                  }}
                  className="text-gray-500 hover:text-gray-700"
                >
                  <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              </div>
            </div>

            <div className="p-6">
              <div className="mb-6">
                <h3 className="font-semibold mb-2">Metadata</h3>
                <div className="bg-gray-50 p-4 rounded text-sm space-y-1">
                  <p><span className="font-medium">Author:</span> {selectedPost.author}</p>
                  <p><span className="font-medium">Submitted:</span> {new Date(selectedPost.submitted_for_approval_at).toLocaleString()}</p>
                  {selectedPost.tags && <p><span className="font-medium">Tags:</span> {Array.isArray(selectedPost.tags) ? selectedPost.tags.join(', ') : selectedPost.tags}</p>}
                  {selectedPost.featured_image && <p><span className="font-medium">Featured Image:</span> <a href={selectedPost.featured_image} target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline">View</a></p>}
                </div>
              </div>

              {selectedPost.excerpt && (
                <div className="mb-6">
                  <h3 className="font-semibold mb-2">Excerpt</h3>
                  <p className="text-gray-700 bg-gray-50 p-4 rounded">{selectedPost.excerpt}</p>
                </div>
              )}

              <div className="mb-6">
                <h3 className="font-semibold mb-2">Content</h3>
                <div className="prose max-w-none bg-gray-50 p-4 rounded">
                  <div dangerouslySetInnerHTML={{ __html: selectedPost.content.replace(/\n/g, '<br />') }} />
                </div>
              </div>

              <div className="mb-6">
                <h3 className="font-semibold mb-2">Approval Notes (Optional)</h3>
                <textarea
                  value={approvalNotes}
                  onChange={(e) => setApprovalNotes(e.target.value)}
                  className="w-full border rounded px-3 py-2"
                  rows="3"
                  placeholder="Add any notes about this approval..."
                />
              </div>

              <div className="mb-6">
                <h3 className="font-semibold mb-2 text-red-700">Rejection Reason (if rejecting)</h3>
                <textarea
                  value={rejectionReason}
                  onChange={(e) => setRejectionReason(e.target.value)}
                  className="w-full border rounded px-3 py-2"
                  rows="3"
                  placeholder="Explain why this post is being rejected..."
                />
              </div>

              <div className="flex gap-4">
                <button
                  onClick={() => handleApprove(selectedPost.id, true)}
                  className="flex-1 bg-green-600 text-white px-6 py-3 rounded-lg hover:bg-green-700 font-medium"
                >
                  ✓ Approve & Publish
                </button>
                <button
                  onClick={() => handleApprove(selectedPost.id, false)}
                  className="flex-1 bg-blue-600 text-white px-6 py-3 rounded-lg hover:bg-blue-700 font-medium"
                >
                  Approve (Don't Publish Yet)
                </button>
                <button
                  onClick={() => handleReject(selectedPost.id)}
                  className="flex-1 bg-red-600 text-white px-6 py-3 rounded-lg hover:bg-red-700 font-medium"
                >
                  ✗ Reject
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default ApprovalQueue;
