"""
TenantGuard User Space — Additional Models
==========================================
Models for the enhanced user dashboard: alerts, motions, and action items.
These extend the existing IntakeSubmission model with case management features.
"""

from django.db import models
from django.utils import timezone


class CaseAlert(models.Model):
    """
    Scheduled alerts for court dates, filing deadlines, and other reminders.
    Alerts are automatically created when the AI analysis detects deadlines,
    and can also be manually created by the user.
    """

    ALERT_TYPES = [
        ("court_date", "Court Date Reminder"),
        ("filing_deadline", "Filing Deadline"),
        ("response_due", "Response Due Date"),
        ("advice_ready", "New Advice Available"),
        ("document_request", "Document Requested"),
        ("custom", "Custom Reminder"),
    ]

    DELIVERY_METHODS = [
        ("sms", "SMS"),
        ("email", "Email"),
        ("both", "SMS + Email"),
    ]

    STATUS_CHOICES = [
        ("pending", "Pending"),
        ("sent", "Sent"),
        ("failed", "Failed"),
        ("cancelled", "Cancelled"),
    ]

    submission = models.ForeignKey(
        "IntakeSubmission",
        on_delete=models.CASCADE,
        related_name="alerts",
    )
    alert_type = models.CharField(max_length=30, choices=ALERT_TYPES)
    delivery_method = models.CharField(
        max_length=10, choices=DELIVERY_METHODS, default="both"
    )
    scheduled_for = models.DateTimeField(
        help_text="When this alert should be sent"
    )
    message = models.TextField(
        help_text="The alert message content"
    )
    status = models.CharField(
        max_length=15, choices=STATUS_CHOICES, default="pending"
    )
    sent_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["scheduled_for"]
        verbose_name = "Case Alert"
        verbose_name_plural = "Case Alerts"

    def __str__(self):
        return f"{self.get_alert_type_display()} — {self.submission.full_name} ({self.scheduled_for:%Y-%m-%d})"

    @property
    def is_overdue(self):
        return self.status == "pending" and self.scheduled_for < timezone.now()


class CaseMotion(models.Model):
    """
    AI-generated motion templates for the tenant's case.
    Each motion includes the full text, filing instructions, and status tracking.
    Motions are generated based on the AI analysis of uploaded documents.
    """

    MOTION_TYPES = [
        ("answer", "Answer to Complaint"),
        ("continuance", "Motion for Continuance"),
        ("dismiss", "Motion to Dismiss"),
        ("discovery", "Discovery Request"),
        ("stay", "Motion to Stay Execution"),
        ("repair_escrow", "Rent Escrow / Repair Request"),
        ("transfer", "Motion to Transfer Venue"),
        ("fee_waiver", "Fee Waiver Application"),
        ("other", "Other Filing"),
    ]

    STATUS_CHOICES = [
        ("draft", "Draft"),
        ("ready", "Ready to File"),
        ("filed", "Filed"),
        ("rejected", "Rejected — Needs Revision"),
    ]

    submission = models.ForeignKey(
        "IntakeSubmission",
        on_delete=models.CASCADE,
        related_name="motions",
    )
    motion_type = models.CharField(max_length=30, choices=MOTION_TYPES)
    title = models.CharField(max_length=255)
    content = models.TextField(
        help_text="The full motion text (Markdown formatted)"
    )
    instructions = models.TextField(
        help_text="Step-by-step filing instructions for the tenant"
    )
    filing_deadline = models.DateField(
        null=True,
        blank=True,
        help_text="Deadline to file this motion",
    )
    court_name = models.CharField(
        max_length=255,
        blank=True,
        default="",
        help_text="Which court to file with",
    )
    filing_fee = models.CharField(
        max_length=50,
        blank=True,
        default="",
        help_text="Expected filing fee (or 'Fee waiver available')",
    )
    status = models.CharField(
        max_length=15, choices=STATUS_CHOICES, default="draft"
    )
    generated_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-generated_at"]
        verbose_name = "Case Motion"
        verbose_name_plural = "Case Motions"

    def __str__(self):
        return f"{self.title} — {self.submission.full_name}"


class CaseActionItem(models.Model):
    """
    Checklist items for the tenant's action plan.
    Generated by AI analysis and can be marked complete by the user.
    Ordered by priority and due date.
    """

    PRIORITY_CHOICES = [
        ("critical", "Critical — Do Today"),
        ("high", "High — This Week"),
        ("medium", "Medium — Before Court Date"),
        ("low", "Low — When Possible"),
    ]

    submission = models.ForeignKey(
        "IntakeSubmission",
        on_delete=models.CASCADE,
        related_name="action_items",
    )
    title = models.CharField(max_length=255)
    description = models.TextField(
        help_text="Detailed explanation of what to do and why"
    )
    priority = models.CharField(max_length=15, choices=PRIORITY_CHOICES)
    due_date = models.DateField(
        null=True,
        blank=True,
        help_text="When this should be completed by",
    )
    completed = models.BooleanField(default=False)
    completed_at = models.DateTimeField(null=True, blank=True)
    order = models.IntegerField(
        default=0,
        help_text="Display order within the same priority level",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = [
            models.Case(
                models.When(priority="critical", then=0),
                models.When(priority="high", then=1),
                models.When(priority="medium", then=2),
                models.When(priority="low", then=3),
                default=4,
                output_field=models.IntegerField(),
            ),
            "order",
            "due_date",
        ]
        verbose_name = "Action Item"
        verbose_name_plural = "Action Items"

    def __str__(self):
        status = "✓" if self.completed else "○"
        return f"{status} [{self.get_priority_display()}] {self.title}"

    def mark_complete(self):
        self.completed = True
        self.completed_at = timezone.now()
        self.save(update_fields=["completed", "completed_at"])

    def mark_incomplete(self):
        self.completed = False
        self.completed_at = None
        self.save(update_fields=["completed", "completed_at"])


class DocumentAnalysis(models.Model):
    """
    Stores the AI analysis result for each uploaded document.
    Links to an IntakeDocument and contains the extracted information.
    """

    DOCUMENT_CATEGORIES = [
        ("eviction_notice", "Eviction Notice"),
        ("court_summons", "Court Summons / Detainer Warrant"),
        ("lease_agreement", "Lease Agreement"),
        ("correspondence", "Landlord Correspondence"),
        ("payment_record", "Payment Record"),
        ("photo_evidence", "Photo Evidence"),
        ("court_order", "Court Order"),
        ("other", "Other Document"),
    ]

    document = models.OneToOneField(
        "IntakeDocument",
        on_delete=models.CASCADE,
        related_name="analysis",
    )
    category = models.CharField(
        max_length=30,
        choices=DOCUMENT_CATEGORIES,
        blank=True,
        default="",
    )
    extracted_text = models.TextField(
        blank=True,
        default="",
        help_text="Full text extracted from the document via OCR/GPT-4o",
    )
    summary = models.TextField(
        blank=True,
        default="",
        help_text="Plain-English summary of what this document means",
    )
    key_dates = models.JSONField(
        default=list,
        blank=True,
        help_text="List of dates found: [{label, date, is_deadline}]",
    )
    legal_issues = models.JSONField(
        default=list,
        blank=True,
        help_text="Legal issues identified: [{issue, severity, explanation}]",
    )
    procedural_defects = models.JSONField(
        default=list,
        blank=True,
        help_text="Potential procedural defects: [{defect, explanation, actionable}]",
    )
    tenant_rights = models.JSONField(
        default=list,
        blank=True,
        help_text="Applicable tenant rights: [{right, statute, explanation}]",
    )
    raw_analysis = models.JSONField(
        default=dict,
        blank=True,
        help_text="Full raw AI analysis response for reference",
    )
    analyzed_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Document Analysis"
        verbose_name_plural = "Document Analyses"

    def __str__(self):
        return f"Analysis of {self.document.original_filename}"
